openapi: 3.0.0
info:
  title: AI Processing API
  description: Core AI processing and agent management
  version: 1.0.0

paths:
  /ai/process:
    post:
      summary: Process AI request
      operationId: processAiRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AiRequest'
      responses:
        '200':
          description: AI processing result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AiResponse'

components:
  schemas:
    AiRequest:
      type: object
      properties:
        query:
          type: string
        type:
          type: string
          enum: [creative, analytical, security]

    AiResponse:
      type: object
      properties:
        content:
          type: string
        confidence:
          type: number
          format: float
        agent:
          type: string
