openapi: 3.0.0
info:
  title: sandbox-api API
  description: Minimal API specification
  version: 1.0.0

paths:
  /status:
    get:
      summary: Get status
      operationId: getStatus
      responses:
        '200':
          description: Status retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
